### ISSUE TITLE
Add nonlin to sample layers

### ISSUE THREAD

**Issue by skaae** [casperkaae/parmesan#24]
Can we make the exp nonlinearity optional in the sample layers by adding a nonlinearity keyword. That would allow for softplus etc. 

add the argument: 

``nonlinearity=lambda x: T.exp(0.5*x)``

**Comment by casperkaae** [comment]
Yes - I'll at that option to the sample layer

closed via commit 06a60e13f72970b6ba06e724728b1a6107f30147
