### ISSUE TITLE
None of examples work

### ISSUE THREAD

**Issue by Ferrine** [casperkaae/parmesan#41]
Hi, I was trying to refactor code to be compatible with python3 but got stuck with not working examples.
I ran them with python2 following installation instructions and having other dependencies and got the same error:
```bash
Exception: Compilation failed (return status=1): clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sse4a'
...
```
I have no idea what causes it

**Comment by casperkaae** [comment]
Hi Ferrine

Yes unfortunately Parmesan is not compatible with python3. I don't think that this error is related to parmesan since you shouldn't need to compile anything for installing the lib?

Maybe there is something wrong in theano or numpy?

Casper

**Comment by Ferrine** [comment]
Examples with latest theano release 0.8.2 work, I think it's better to change the requirements

**Comment by casperkaae** [comment]
That would be great! I have thought about that to but have not got around to it. 

I'll close this issue - just open a new one for the python3 refactoring
